Prefer  X11/etc/X11/xinit over the one in X11/lib if present

diff --git a/sedsrc/update-sys-xinitrc.in b/sedsrc/update-sys-xinitrc.in
--- a/sedsrc/update-sys-xinitrc.in
+++ b/sedsrc/update-sys-xinitrc.in
@@ -2,7 +2,15 @@
 # $Id: update-sys-xinitrc.in,v 1.3 2008/02/27 14:10:00 aida_s Exp $
 set -e
 fink_prefix="@PREFIX@"
-sysxinitdir="/opt/X11/etc/X11/xinit"
+# This works whichever X is in use
+if [[ -d /opt/X11/etc/X11/xinit ]]; then
+	sysxinitdir="/opt/X11/etc/X11/xinit";
+elif [[ -d /opt/X11/lib/X11/xinit ]]; then
+	sysxinitdir="/opt/X11/lib/X11/xinit";
+else
+	echo "xinit dir for X11 not found. Exiting."
+	exit 1;
+fi
 target="$sysxinitdir/xinitrc"
 master="$fink_prefix/share/xinitrc/sys-xinitrc-fink"
 myname="update-sys-xinitrc"
